Documentación de TabRow
ArisGuimera/JetpackComposePro pull request #100
Opened 2024-01-31 18:57 UTC by alejandro342

Se agrego la documentación del composable TabRow.

2024-02-12 18:24 UTC, ArisGuimera requested changes
Te dejé un par de cambios para realizar pero en general está genial :)

2024-02-12 18:24 UTC, ArisGuimera commented on src/content/docs/tabs/tab-row.mdx
> +title: Tab-Row
El guión en medio no va

2024-02-12 18:24 UTC, ArisGuimera commented on src/content/docs/tabs/tab-row.mdx
> + TabRowExample(
Veo que el código está mal formateado además que hay valores que el usuario no sabe de donde salen. Por ejemplo tabIndex.

La idea es que si alguien copia y pega lo que aparece aquí tenga exactamente lo que se ve en la imagen.

2024-02-18 10:04 UTC, ArisGuimera commented
Está genial, lo mandamos a prod!

2024-02-18 10:04 UTC, merged

2024-02-19 17:28 UTC, alejandro342 commented
Gracias