SwipeToDismiss
ArisGuimera/JetpackComposePro pull request #105
Opened 2024-05-26 23:21 UTC by enocgarcia2005

@ArisGuimera Listo el componente SwipeToDismiss

2024-06-05 14:06 UTC, ArisGuimera requested changes

2024-06-05 14:06 UTC, ArisGuimera commented on src/content/docs/swipes/swipe-to-dismiss.mdx
> +```kotlin frame="terminal"
Faltan los tabs si tiene implementaciones distintas en Material/Material3

2024-06-09 01:28 UTC, enocgarcia2005 commented on src/content/docs/swipes/swipe-to-dismiss.mdx
> +```kotlin frame="terminal"
@ArisGuimera en la definición del componente no tiene ningún cambio por ello decidí no poner tabs ya que la definición que esta ahí sirve tanto para material como para material 3

2024-06-09 10:23 UTC, ArisGuimera commented on src/content/docs/swipes/swipe-to-dismiss.mdx
> +```kotlin frame="terminal"
Entonces forma parte de los foundation:

https://www.jetpackcompose.pro/lists/lazy-row/

Sería poner esa tab :)

2024-06-09 17:47 UTC, enocgarcia2005 commented on src/content/docs/swipes/swipe-to-dismiss.mdx
> +```kotlin frame="terminal"
@ArisGuimera Ok perfecto me pongo en ello, y en la parte de los ejemplos lo dejo como está, separado por material y material3?, es que hay cosas por ejemplo la llamada a los colores y en los estados que cambian un poco el nombre por eso los serparé

2024-06-09 18:15 UTC, enocgarcia2005 commented on src/content/docs/swipes/swipe-to-dismiss.mdx
> +```kotlin frame="terminal"
@ArisGuimera mala mía, me puse a investigar por que me pareció raro ya que no era fundation, y lo que sucedió es que de una versión para acá en material3 le cambiaron el nombre al componente, y al parecer yo lo probé en una versión un tanto antigua, por eso era igual la implementación a material, ya mismo me pongo a arreglarlo

2024-06-09 19:48 UTC, enocgarcia2005 commented
@ArisGuimera Listo los cambios

2024-06-10 14:56 UTC, ArisGuimera approved these changes

2024-06-10 14:57 UTC, merged