Create section slider component
ArisGuimera/JetpackComposePro pull request #111
Opened 2024-06-18 13:50 UTC by Iptriana98

2024-06-18 14:42 UTC, ArisGuimera commented
Buenas! Estás on fire 🔥

Si no me equivoco hay un componente específico, no?

2024-06-18 15:12 UTC, Iptriana98 commented
listo, creo que ya está

2024-08-17 07:37 UTC, ArisGuimera requested changes

2024-08-17 07:37 UTC, ArisGuimera commented on src/content/docs/sliders/section-slider.mdx
> +<center>![RangeSlider - Material 3 [DropdownMenu]](../../../assets/sliders/range-sliders/range-slider-material3.png)</center>
Creo que se te coló esto!

2024-08-21 09:34 UTC, Iptriana98 commented on src/content/docs/sliders/section-slider.mdx
> +<center>![RangeSlider - Material 3 [DropdownMenu]](../../../assets/sliders/range-sliders/range-slider-material3.png)</center>
Me pillaste, se me fue del otro componente 😅. Ya lo arreglo

2024-08-21 09:40 UTC, Iptriana98 reviewed
Cambie los nombres de las imágenes que estaban mal

2024-09-02 09:01 UTC, ArisGuimera commented
Eres un fucking crack! Mergeamos 🚀

2024-09-02 09:02 UTC, merged