Añadido el componente `Card` y también aliases de importación
ArisGuimera/JetpackComposePro pull request #4
Opened 2023-12-07 09:57 UTC by BobbyESP

# PR (parte de #1)
Bueno, básicamente lo que hice en esta PR es añadir el componente `Card` y su explicación junto a `CardDefaults`, ya que creo que es importante para entender como se pueden cambiar los colores de las tarjetas.

Junto a esto he añadido los [alias](https://docs.astro.build/es/guides/aliases/) de importación para la carpeta `assets` y `components` (que aunque ahora no esté creada, lo más probable es que en un futuro tenga que estarlo -> [¿Qué son?](https://docs.astro.build/es/core-concepts/astro-components/)).

## Cambios
- Añadido el componible `Card`
- Movida la llamada de imágenes de `../../../assets` a `@assets`

2023-12-13 06:56 UTC, ArisGuimera requested changes
Falta meterlo con Material, solo está Material 3, de resto todo perfecto.

Muchas gracias

2023-12-13 06:57 UTC, BobbyESP commented
> Falta meterlo con Material, solo está Material 3, de resto todo perfecto.
> 
> Muchas gracias

Verdad. Después lo cambio!

2024-01-24 21:05 UTC, BobbyESP commented
No está olvidado gente, pero los exámenes de 2do de bach me imposibilitan un poquito lo que es acabrlo

2024-01-24 22:49 UTC, BobbyESP commented
Y debería estar acabado @ArisGuimera

2024-01-25 18:20 UTC, BobbyESP commented
He leído por ahí que no debemos usar imágenes directamente de la documentación de Google puede ser?

2024-01-26 07:15 UTC, ArisGuimera commented
> He leído por ahí que no debemos usar imágenes directamente de la documentación de Google puede ser?

Exacto. 

https://github.com/ArisGuimera/JetpackComposePro/discussions/73

2024-01-26 09:19 UTC, BobbyESP commented
> 
> 
> 
> > He leído por ahí que no debemos usar imágenes directamente de la documentación de Google puede ser?
> 
> Exacto. 
> 
> https://github.com/ArisGuimera/JetpackComposePro/discussions/73

Okeyy, graciass. Después la cambio

2024-02-12 18:02 UTC, ArisGuimera commented
¿Tenemos novedades? Sino tenemos que volver a asignarla!

2024-02-12 18:10 UTC, BobbyESP commented
Perdónn! Hoy hago las capturas y ya debería estar, lo siento!

2024-02-12 18:46 UTC, ArisGuimera requested changes
Te he dejado algunos comentarios, échale un ojo a cualquier componente ya hecho para que te hagas una idea si quieres sobre lo de las tabs que te comento.

Un abrazo!

2024-02-12 18:46 UTC, ArisGuimera commented on src/content/docs/cards/card.mdx
> +| Material 3 (Claro)                                            | Material 3 (Oscuro)                                          |
Las tabs deberían ser Material y Material 3

2024-02-12 18:46 UTC, ArisGuimera commented on src/content/docs/cards/card.mdx
> +|onClick | Función que se ejecutará cuando se haga click en la tarjeta.|
Los atributos no concuerdan con la definición del componente.

2024-02-12 18:46 UTC, ArisGuimera commented on src/content/docs/cards/card.mdx
> +```kotlin frame="terminal"
Esto sigue mal!

2024-02-12 18:51 UTC, BobbyESP commented
> Te he dejado algunos comentarios, échale un ojo a cualquier componente ya hecho para que te hagas una idea si quieres sobre lo de las tabs que te comento.
> 
> Un abrazo!

Okeyy, gracias! Intentaré hacer los cambios lo antes posible. Siento el retraso 💀

2024-03-13 20:32 UTC, ArisGuimera commented
Buenas, voy a tener que cerrar esta PR y asignarselo a otra persona que hay que ir cerrando esto ya.

Un saludo

2024-03-13 22:40 UTC, BobbyESP commented
> Buenas, voy a tener que cerrar esta PR y asignarselo a otra persona que hay que ir cerrando esto ya.
> 
> Un saludo

Me parece correcto. Siento las molestias Aris. Cuando tenga más tiempo volveré a colaborar en el proyecto y no dejar las cosas a medias 🙏

2024-04-10 14:48 UTC, closed without merging