add document compose Chip
ArisGuimera/JetpackComposePro pull request #9
Opened 2023-12-13 23:33 UTC by LucasGinard

## Cambios 🚀:
Buenas Aris agregue la documentación de `Chip`  al ser un elemento padre que se usa por debajo de los otros Chips agregue los 4 tipos de `Chips` que existen actualmente igualmente puse los parámetros que usa el composable `Chip`.

También agregue una imagen que muestra los dos chips de material design 2 y 3 y al ser transparente queda bien en modo oscuro y claro o deberia tener un color fijo ?

<img src="https://github.com/ArisGuimera/JetpackComposePro/assets/57275367/7441d253-b5d6-4313-9810-74056acfd361" height="300"/>

Para los parametros lo hizo como una tabla creo que queda mejor que ponerlo como lista o es fijo utilizarlo ?
<img src="https://github.com/ArisGuimera/JetpackComposePro/assets/57275367/99c75160-1e1a-4acb-96df-d352564233b1" height="300"/>

2023-12-14 00:22 UTC, OrlanDroyd commented
Personalmente me gustó en forma de tabla, @ArisGuimera en caso de que decidas que queda mejor así lo comentas y actualizamos el template y de paso yo cambio también el componente `Switch` que ya aprobaste :)

2023-12-16 00:34 UTC, LucasGinard commented
Lo puedes revisar cuando puedas porfa @ArisGuimera 
<img src="https://media.tenor.com/zNGKGnXxmN4AAAAM/cozy-peepo.gif"/>

2023-12-19 06:58 UTC, ArisGuimera commented
Buenas, te dejé un comentario pero veo que no está puesto todavía no? Hay que añadir ejemplos. Puedes mirar de guía el componente Button que está cerrado 100%

2023-12-20 17:55 UTC, ArisGuimera requested changes

2023-12-20 17:55 UTC, ArisGuimera commented on src/content/docs/chips/chip.mdx
> +## El composable `Chip` se divide en cuatro tipos distintos, cada uno diseñado con un propósito específico:
No crees que deberían ser 4 componentes distintos? Por ejemplo si te fijas en los botones son básicamente el mismo pero tienen finalidades distintas por lo que están separados ya que puede que haya gente que busque por ejemplo un OutlinedButton y si está dentro del button no lo encuentra.

¿Qué piensas?

2023-12-21 00:36 UTC, LucasGinard commented on src/content/docs/chips/chip.mdx
> +## El composable `Chip` se divide en cuatro tipos distintos, cada uno diseñado con un propósito específico:
Sii así queda mas corto la documentación, lo cambio 👍

2023-12-23 17:26 UTC, LucasGinard commented
Ya están separados cada tipo de `chip`  para compose solo están disponible desde material 3 estos composables.

Aguardo feedback @ArisGuimera 😁

2023-12-24 11:01 UTC, ArisGuimera commented
Está casi casi PERFECTO y te prometo que me da apuro ser tan tiquismiquis, pero te propongo un par de cambios para dejarlo EXACTO a los otros componentes ya que la idea es que sea completamente homogéneo.

Uso de ejemplo `AssistChip` pero los cambios hay que aplicarlos a todos.

La primera imagen la tienes así:

<center>![Imagen del componente Button - Material 3](../../../assets/chip/assist-chip/chip-assist-material-3-example.webp)</center>

Ahí tienes que cambiarle la descripción que sigue poniendo Button y luego esta primera imagen va en una tabla (como aquí https://www.jetpackcompose.pro/buttons/filled-tonal-button/) con el título de Material 3 para que cuando entren puedan ver que es solo para material 3. Y esta imagen no va centrada, va a la izquierda como el texto.

Luego en la parte de ejemplos cambiar el título y dejar solo `### Ejemplo` que es como están todos los otros componentes.

De resto está perfecto, muchísimas gracias por tu ayuda 💯

2023-12-24 12:08 UTC, ArisGuimera commented
Ahhh y la descripción del componente ¿La puedes poner como un párrafo? Ej:

- **Propósito:** Orienta al usuario durante una tarea.
- **Apariencia:** Suelen ser elementos temporales que aparecen en respuesta a las acciones del usuario.
- **Ejemplo de Uso:** Guiar al usuario a través de un flujo de trabajo o proporcionar información relevante en un contexto específico.

El componente `AssistChip` está destinado a orientar al usuario durante una tarea, su apariencia suele ser para elementos temporales que aparecen en... etc

2023-12-24 18:37 UTC, LucasGinard commented
Listo aguardo feedback 
<img src="https://media3.giphy.com/media/yxicUANit7fTdEdZgr/200w.gif" />

2023-12-25 11:56 UTC, ArisGuimera approved these changes
PERFECTO 🚀

2023-12-25 11:56 UTC, merged