DropdownMenuItem
ArisGuimera/JetpackComposePro pull request #91
Opened 2024-01-27 03:07 UTC by jamirou

- [x] Añadir documentación del componente DropdownMenuItem.
 - [x] Añadir imágenes del componente.
 - [x] issue #56

2024-02-08 08:01 UTC, ArisGuimera requested changes
A parte del comentario que te dejé estoy viendo que tu ejemplo es de un dropdown completo (al igual que las imágenes) este componente es el DropdownmenuItem por lo que solo debería mostrar ese componente. No se si me entiendes.

Un saludo

2024-02-12 18:03 UTC, ArisGuimera commented on src/content/docs/menus/dropdown-menu-item.mdx
> -description: Aprende a usar el composable DropdownMenuItem en Jetpack Compose.
@jamirou

2024-02-22 14:28 UTC, jamirou commented on src/content/docs/menus/dropdown-menu-item.mdx
> -description: Aprende a usar el composable DropdownMenuItem en Jetpack Compose.
Perdon la tardanza @ArisGuimera he estado un poco ocupado pero hare la correccion!
Entonces solo debo mostrar los iconos del dropdown (en las imagenes) y el codigo lo dejare sin el dropdown entonces. Lo habia creado de esa manera ya que me parece mas entendible incluir el dropdown para un mejor entendimiento del usuario ya que por algo se llama asi jaja. Pero no hay problem Aris!

2024-03-13 20:36 UTC, ArisGuimera commented
Buenas, tu PR está PERFECTA pero técnicamente no es un DropDownMenuItem sino un DropdownMenu. Como parece que el chico que se había asignado el DropDownMenu no dio nunca señales de vida, te parece que lo cambies al fichero de DropDownMenu y lo mergeamos como definición de ese componente?

PD: Felicidades porque te quedó genial

2024-03-14 02:27 UTC, jamirou commented
Gracais Aris por tu feedback, ya he realizado los cambios sin problemas, solo un pequeno detalle con la pull pero ya ha sido resuelto:)

2024-03-14 07:51 UTC, ArisGuimera commented
Está genial, mergeamos!

2024-03-14 07:51 UTC, merged