LazyColumn
ArisGuimera/JetpackComposePro pull request #94
Opened 2024-01-28 15:26 UTC by SantipBarber

Hola Aris!

Perdón por la tardanza, pero esta semana ha sido una locura en el curro. 

Te paso la pull request para que revises. Cualquier cosa me comentas.

Gracias por dejarnos participar y un saludo!!!

2024-02-07 17:41 UTC, SantipBarber commented
Buenas Aris!

Falta alguna cosa con esta issue? #94

Gracias y un saludo

2024-02-07 17:43 UTC, SantipBarber commented
Perdón, esta #53

2024-02-08 08:08 UTC, ArisGuimera requested changes
Te he dejado un par de cambios pero en general está muy bien :)

2024-02-08 08:08 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +
Faltan las imágenes aquí (mirar cualquier componente)

2024-02-08 08:08 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +El componente LazyColumn de Jetpack Compose es una alternativa eficiente a RecyclerView para manejar listas verticales. Pero a diferencia de éste, que carga todas las vistas necesarias para llenar la
El párrafo es bastante largo, hay que poner algún punto y aparte por tema seo.

2024-02-08 08:08 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +modifier | El modificador a aplicar a este diseño. <a style="text-decoration: none;" href="https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier">🔗</a>
Hay que quitar esos links con ese icono. La idea es buena pero hay que buscar una solución, decidirla y luego ponerla en práctica ya que los otros componentes no lo tienen.

2024-02-08 08:08 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +<center>![Imagen del componente LazyColumn - Material3](../../../assets/lazy-column/simple_lazy_column.gif)</center>
Los gif pesan MUCHO, hay que reemplazarlos por imágenes o que pesen menos de 500kb.

2024-02-13 16:21 UTC, SantipBarber commented
Buenas Aris!

He añadido los cambios que me comentaste. Échale un vistazo y me comentas.

Un saludo ;)

2024-02-13 16:22 UTC, SantipBarber commented on src/content/docs/lists/lazy-column.mdx
> +<center>![Imagen del componente LazyColumn - Material3](../../../assets/lazy-column/simple_lazy_column.gif)</center>
Hecho

2024-02-13 16:22 UTC, SantipBarber commented on src/content/docs/lists/lazy-column.mdx
> +modifier | El modificador a aplicar a este diseño. <a style="text-decoration: none;" href="https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier">🔗</a>
Hecho

2024-02-13 16:22 UTC, SantipBarber commented on src/content/docs/lists/lazy-column.mdx
> +
Hecho

2024-02-18 09:57 UTC, ArisGuimera requested changes
Te dejé un par de comentarios más y ya estaría perfecto!

2024-02-18 09:57 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +| Material 3 |
Realmente no es material 3, es Foundation

2024-02-18 09:57 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +```kotlin
Te falto el tab 

</TabItem>
<TabItem label="Foundation">

2024-02-18 09:57 UTC, ArisGuimera commented on src/content/docs/lists/lazy-column.mdx
> +<Tabs>
Para el tema de los ejemplos si te parece ponemos solo un tab Foundation y dentro los 2 ejemplos (con un título cada uno)

2024-02-24 16:29 UTC, SantipBarber commented on src/content/docs/lists/lazy-column.mdx
> +<Tabs>
Ok, subo la corrección y me comentas. Cambié el título de LazyColumn con cabecera por LazyColumn con encabezados, que me parece más correcto. Si quieres que ponga otro nombre lo comentamos.

2024-02-24 16:34 UTC, SantipBarber commented
> Te dejé un par de comentarios más y ya estaría perfecto!

Ya subí los cambios. Un saludo ;)

2024-03-13 20:30 UTC, ArisGuimera commented
Está perfecto, mergeamos!!!

2024-03-13 20:30 UTC, merged