Componente tab
ArisGuimera/JetpackComposePro pull request #98
Opened 2024-01-31 02:45 UTC by ronald-bismar

Documentación del componente Tab

2024-02-12 18:10 UTC, ArisGuimera requested changes
@ronald-bismar Te he dejado algunos comentarios. 

Muchas gracias!

2024-02-12 18:10 UTC, ArisGuimera commented on src/content/docs/home/guide.mdx
> -    <ExpandLinkCard
Estos cambios están dando conflictos

2024-02-12 18:10 UTC, ArisGuimera commented on src/content/docs/tabs/tab.mdx
> +![Tab](../../../assets/tab/tab-header.webp)
¿La imagen la hiciste tú? No podemos usar imágenes de la documentación de Google, además hay que usar una tabla para mostrar las imágenes de cada material

2024-02-12 18:10 UTC, ArisGuimera commented on src/content/docs/tabs/tab.mdx
> +| content                 | Representa el contenido del `tab`
este atributo no está en el composable

2024-02-12 18:10 UTC, ArisGuimera commented on src/content/docs/tabs/tab.mdx
> +<TabItem label="Tabs Secundarios">
Los tabs van en relación a cada material. Por ejemplo Material (y aquí dentro poner todos los ejemplos que quieras de esta versión) y material 3 (y lo mismo). 

Te pongo un ejemplo https://www.jetpackcompose.pro/buttons/button/

2024-02-23 19:45 UTC, ronald-bismar commented
Ok Aris me pongo a corregir los conflictos

2024-02-25 23:58 UTC, ronald-bismar commented
@ArisGuimera te mando los cambios que le hice a la documentación del componente Tab, por favor revísalos Saludos

2024-03-13 20:29 UTC, ArisGuimera commented
> @ArisGuimera te mando los cambios que le hice a la documentación del componente Tab, por favor revísalos Saludos

Buenas, parece que la tabla de atributos se te rompió

2024-06-05 14:07 UTC, ArisGuimera commented
@ronald-bismar

2024-06-10 15:10 UTC, ArisGuimera commented
@ronald-bismar último aviso antes de cerrar la PR!

2024-06-11 09:24 UTC, ArisGuimera commented
cerramos aquí ya que se hizo otra PR

https://github.com/ArisGuimera/JetpackComposePro/pull/106

2024-06-11 09:24 UTC, closed without merging