LazyRow documentación lista
ArisGuimera/JetpackComposePro pull request #99
Opened 2024-01-31 05:48 UTC by ernesto-ca

Hola Aris, lista la documentacion del componete LazyRow:
issue: https://github.com/ArisGuimera/JetpackComposePro/issues/54

- [x] Definición de el componente e imagen
- [x] Descripción de los atributos
- x ] Ejemplo por cada modo de implementación

![image](https://github.com/ArisGuimera/JetpackComposePro/assets/71567859/8c271ef0-cea2-46b4-a15a-ec452a369a81)

2024-02-12 18:19 UTC, ArisGuimera requested changes
Te he dejado algunos comentarios, en general está bastante bien pero hay que hacer algún cambio.

Muchas gracias!

2024-02-12 18:19 UTC, ArisGuimera commented on src/content/docs/lists/lazy-row.mdx
> +El `LazyRow` es un componente que fue agregado oficalmente en la versión 1.2 de Jetpack Compose, antes de este existió el `ScrollableRow` pero este ha sido removido de toda documentación oficial
Si te parece hacemos que el primer párrafo sea la explicación específica del componente y luego puedes poner un par de párrafos más explicando todo eso, pero la idea es que si alguien llega con leer solo las 2 primeras líneas sepa que hace el componente

2024-02-12 18:19 UTC, ArisGuimera commented on src/content/docs/lists/lazy-row.mdx
> +![Imagen de ejemplo de uso de LazyRow](../../../assets/lists/lazyrow/lazyRow.png)
¿Te parece recortar un poco la imagen? Por arriba y por abajo hay bastante blanco, está bien pero yo le quitaría un 30% más o menos en la altura

2024-02-12 18:19 UTC, ArisGuimera commented on src/content/docs/lists/lazy-row.mdx
> +```kotlin frame="terminal"
Falta meterle el TabItem, como no es material ni material 3 habría que poner Foundation.

```
</TabItem>
<TabItem label="Foundation">
```

2024-02-12 18:19 UTC, ArisGuimera commented on src/content/docs/lists/lazy-row.mdx
> +): Unit
hay que quitar el `: Unit`

2024-02-12 18:19 UTC, ArisGuimera commented on src/content/docs/lists/lazy-row.mdx
> +<TabItem label="LazyRow - item">
Los tabs son para los tipos distintos de librerías (Foundation, Material, Material 3...) así que si te parece puedes poner todos dentro de una tab Foundation y ponerlos uno debajo de otro (puedes usar un pequeño título).

Y puedes recortar un poco las imágenes? Que se vea solo la lista y no todo el móvil si te parece.

2024-02-18 10:02 UTC, ArisGuimera commented
Buenas, te sigue faltando el tab en la definición del componente, el resto está perfecto!

2024-02-27 04:04 UTC, ernesto-ca commented
> Buenas, te sigue faltando el tab en la definición del componente, el resto está perfecto!

Lo siento Aris no entendí tu observación.  ¿A que tab te refieres? por que ya tengo la de Fundation o ¿debería tambien agregar otra tabla en la definición junto a la imagen?

2024-03-13 20:28 UTC, ArisGuimera commented
> > Buenas, te sigue faltando el tab en la definición del componente, el resto está perfecto!
> 
> Lo siento Aris no entendí tu observación. ¿A que tab te refieres? por que ya tengo la de Fundation o ¿debería tambien agregar otra tabla en la definición junto a la imagen?

Fíjate que en los ejemplos tienes una pestañita que pone foundation, hay que ponerlo también en la definición del código , justo donde está lo de "El componente se ha mantenido igual desde su versión en Jetpack Compose [1.2](https://developer.android.com/jetpack/androidx/releases/compose-foundation?hl=es-419#1.2.0)"

2024-03-20 05:02 UTC, ernesto-ca commented
> > > Buenas, te sigue faltando el tab en la definición del componente, el resto está perfecto!
> > 
> > 
> > Lo siento Aris no entendí tu observación. ¿A que tab te refieres? por que ya tengo la de Fundation o ¿debería tambien agregar otra tabla en la definición junto a la imagen?
> 
> Fíjate que en los ejemplos tienes una pestañita que pone foundation, hay que ponerlo también en la definición del código , justo donde está lo de "El componente se ha mantenido igual desde su versión en Jetpack Compose [1.2](https://developer.android.com/jetpack/androidx/releases/compose-foundation?hl=es-419#1.2.0)"

Listo! muchas gracias por la explicación

2024-05-01 09:15 UTC, ArisGuimera approved these changes

2024-05-01 09:15 UTC, ArisGuimera commented
A prod! Graciassss

2024-05-01 09:15 UTC, merged